# Generated by Django 3.0.5 on 2021-05-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('reciver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_id', to='unthoughtApp.Member')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_2', to='unthoughtApp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualChatList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name_1', models.CharField(max_length=50)),
                ('member_name_2', models.CharField(max_length=50)),
                ('member_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_id_1', to='unthoughtApp.Member')),
                ('member_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_id_2', to='unthoughtApp.Member')),
            ],
        ),
    ]
