# Generated by Django 3.0.5 on 2020-12-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='unique_name',
            new_name='unique_nam',
        ),
    ]
