# Generated by Django 3.0.5 on 2020-12-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0002_auto_20201214_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='unique_nam',
        ),
    ]
