# Generated by Django 3.0.5 on 2021-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0003_auto_20210524_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualchatlist',
            old_name='seen',
            new_name='member_1_seen',
        ),
        migrations.AddField(
            model_name='individualchatlist',
            name='member_2_seen',
            field=models.BooleanField(default=False),
        ),
    ]
