# Generated by Django 3.0.5 on 2020-12-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0003_remove_member_unique_nam'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unique_name',
            field=models.CharField(default='ashish', max_length=50),
            preserve_default=False,
        ),
    ]
