# Generated by Django 3.0.5 on 2020-12-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0004_member_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='pri_specification_submain',
            field=models.CharField(default='App Development', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmember',
            name='progress_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventspics',
            name='event_dp',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='eventPic/'),
        ),
        migrations.AlterField(
            model_name='eventspics',
            name='event_pic1',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='eventPic/'),
        ),
        migrations.AlterField(
            model_name='eventspics',
            name='event_pic2',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='eventPic/'),
        ),
        migrations.AlterField(
            model_name='memberdp',
            name='member_dp',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='memberDp/'),
        ),
        migrations.AlterField(
            model_name='postpic',
            name='post_dp',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='postPic/'),
        ),
        migrations.AlterField(
            model_name='postpic',
            name='post_pic1',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='postPic/'),
        ),
        migrations.AlterField(
            model_name='postpic',
            name='post_pic2',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='postPic/'),
        ),
    ]
