# Generated by Django 3.0.5 on 2020-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0005_auto_20201221_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(),
        ),
    ]
