# Generated by Django 3.0.5 on 2021-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0005_individualchatlist_last_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualchatlist',
            name='last_message_date',
            field=models.DateTimeField(),
        ),
    ]
