# Generated by Django 3.0.5 on 2021-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0006_auto_20201221_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedpostmember',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savepostmember',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
