# Generated by Django 3.0.5 on 2021-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0007_auto_20210506_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspics',
            name='categories',
            field=models.CharField(default='web development', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventspics',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventspics',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
