# Generated by Django 3.0.5 on 2021-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0007_auto_20210524_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=50)),
                ('user_number', models.CharField(max_length=10)),
                ('user_desc', models.CharField(max_length=900)),
            ],
        ),
    ]
