# Generated by Django 3.0.5 on 2021-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0008_auto_20210507_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspics',
            name='date',
            field=models.DateField(),
        ),
    ]
