# Generated by Django 3.0.5 on 2021-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0008_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
