# Generated by Django 3.0.5 on 2021-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0009_auto_20210507_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
