# Generated by Django 3.0.5 on 2021-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unthoughtApp', '0009_projectmember_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpic',
            name='progress_status',
            field=models.IntegerField(default=0),
        ),
    ]
